version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=teste
      - MYSQL_PASSWORD=teste
      - MYSQL_USER=caracore_checklist
      - MYSQL_DATABASE=caracore_checklist